"""Migrando com novos atributos de Anuncio

Revision ID: 5ce5097d19f4
Revises: c4d51a38a571
Create Date: 2024-12-07 18:47:32.383225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ce5097d19f4'
down_revision = 'c4d51a38a571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anuncios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preco', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anuncios', schema=None) as batch_op:
        batch_op.drop_column('preco')

    # ### end Alembic commands ###
