"""Atualizando modelo Leo

Revision ID: 7b6eb2615eb1
Revises: 5ce5097d19f4
Create Date: 2024-12-27 18:58:29.402235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b6eb2615eb1'
down_revision = '5ce5097d19f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anuncios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('imagem', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anuncios', schema=None) as batch_op:
        batch_op.drop_column('imagem')
        batch_op.drop_column('titulo')

    # ### end Alembic commands ###
