"""empty message

Revision ID: c4b1432e51b1
Revises: 55ded16d4c5a
Create Date: 2024-11-20 13:29:08.381965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4b1432e51b1'
down_revision = '55ded16d4c5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anuncios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anunciante', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('telefone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('local', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('categoria', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tipo', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('nota', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), nullable=True))
        batch_op.alter_column('descricao',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'categorias', ['categoria'], ['id'])
        batch_op.create_foreign_key(None, 'tipos', ['tipo'], ['id'])
        batch_op.create_foreign_key(None, 'perfis', ['anunciante'], ['id'])
        batch_op.drop_column('nome')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anuncios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('descricao',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.drop_column('ativo')
        batch_op.drop_column('nota')
        batch_op.drop_column('tipo')
        batch_op.drop_column('categoria')
        batch_op.drop_column('local')
        batch_op.drop_column('telefone')
        batch_op.drop_column('anunciante')

    # ### end Alembic commands ###
