"""Alterado tipo campo senha em Perfil

Revision ID: c4d51a38a571
Revises: fcd5279e1602
Create Date: 2024-12-03 23:32:26.846325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d51a38a571'
down_revision = 'fcd5279e1602'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfis', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfis', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
