"""empty message

Revision ID: f85995e11176
Revises: 7b6eb2615eb1
Create Date: 2025-01-09 11:28:22.742620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f85995e11176'
down_revision = '7b6eb2615eb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('anuncio', sa.Integer(), nullable=True),
    sa.Column('interessado', sa.Integer(), nullable=True),
    sa.Column('nota_interessado', sa.Integer(), nullable=True),
    sa.Column('nota_anunciante', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['anuncio'], ['anuncios.id'], ),
    sa.ForeignKeyConstraint(['interessado'], ['perfis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transacoes')
    # ### end Alembic commands ###
